kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: welcome-argocd-argocd-dex-server
  namespace: welcome-gitops
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: welcome-argocd-argocd-dex-server
  namespace: welcome-gitops
subjects:
  - kind: ServiceAccount
    name: welcome-argocd-argocd-dex-server
    namespace: welcome-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: welcome-argocd-argocd-dex-server

