# These overrides are appropriate defaults for deploying this chart on OpenShift

vault:
  fullnameOverride: hvault
  
  global:
    openshift: true

  injector:
    enabled: false
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
      tag: "1.0.0-ubi"

    agentImage:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.11.3-ubi"

  server:
    route:
      enabled: true
      host: hvault.paas-03.test.net.intra.xxxx.fr
      tls:
        termination: edge
    dev:
      enabled: false
    image:
      repository: "registry.connect.redhat.com/hashicorp/vault"
      tag: "1.11.3-ubi"

    dataStorage:
      size: 1Gi

    postStart:
      - /bin/sh
      - -c
      - ( sleep 10 && vault operator unseal $UNSEAL_KEY ) & exit 0

    extraSecretEnvironmentVars:
      - envName: UNSEAL_KEY
        secretName: unseal-key
        secretKey: KEY
