apiVersion: v1
data:
  AVP_AUTH_TYPE: azhz
  AVP_K8S_ROLE: YXZw
  AVP_KV_VERSION: MQ==
  AVP_TYPE: dmF1bHQ=
  VAULT_ADDR: aHR0cDovL2h2YXVsdDo4MjAw
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: avp-config
