apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: gitea-cli-job-sa-role
rules:
  - apiGroups:
      - gpte.opentlc.com
      - apiextensions.k8s.io
    resources:
      - giteas
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: gitea-cli-job-sa-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitea-cli-job-sa-role
subjects:
  - kind: ServiceAccount
    name: gitea-cli-job-sa
    namespace: scm
