apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: gitea-crd-wait-job
  namespace: scm
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.7
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/scm
              echo ""
              echo -n "Waiting for the Gitea CRD to become available"
              sleep $SLEEP
              until oc wait --for condition=established --timeout=60s crd/giteas.gpte.opentlc.com -n scm 2>&1 >/dev/null
              do
                echo -n "."
                sleep $SLEEP
              done
              echo -n -e "DONE\n"
          imagePullPolicy: Always
          name: gitea-crd-wait-container
          env:
          - name: SLEEP
            value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: gitea-cli-job-sa
      serviceAccountName: gitea-cli-job-sa
      terminationGracePeriodSeconds: 90
