apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: gitea
  namespace: scm
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  giteaImageTag: 1.14.3
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaAdminPassword: openshift
  giteaAdminUser: gitea-admin
  giteaSsl: true
  giteaVolumeSize: 4Gi
  postgresqlVolumeSize: 4Gi
