apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-read-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-read-secrets
subjects:
  - kind: ServiceAccount
    name: argocd-vault-plugin
    namespace: argocd
