apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 0-cluster-config-appset.yaml

# - 1-lab-vault-demo-appset.yaml
# - 1-tenants-appset.yaml
# - 1-lab-cicd-demo-appset.yaml
# - 1-lab-xxxx-appset.yaml



