apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: welcome-prod
  labels:
    argocd.argoproj.io/managed-by: welcome-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
status: {}
