#  How to use Helm:
#  https://argo-cd.readthedocs.io/en/latest/user-guide/helm/

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
spec:
  project: default

  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.0
    helm:
      releaseName: sealed-secrets
      # valueFiles:
      # - values-xxxx.yaml
      # parameters:
      # - name: "service.type"
      #   value: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true