apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    path: cluster-XXXX/lab-sealed-secrets/sealed-secrets-operator/overlays/default
    repoURL: 'https://github.com/lcolagio/lab-gitops-v2/'
    targetRevision: master
  destination:
#    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true