apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: gt-wait-job
  namespace: welcome-gitops
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.7
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/gt
              echo ""
              echo -n "Waiting for Gitea to finish rolling out"
              sleep $SLEEP
              until oc wait --for condition=complete --timeout=60s jobs/gitea-bootstrap -n scm
              do
                echo -n "."
                sleep $SLEEP
              done
              echo -e "DONE\n"
          imagePullPolicy: Always
          name: gt-wait-container
          env:
          - name: SLEEP
            value: "5"
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
